In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
def tanh(x):
  return (torch.exp(x)-torch.exp(-x)) / (torch.exp(x)+torch.exp(-x))
  
def sigmoid(x):
  return 1 / (1 + torch.exp(-x))

In [6]:
torch.manual_seed(1)

def forward(x, neurons):
  hidden_layer = nn.Linear(torch.flatten(x).size(0), neurons)
  output_layer = nn.Linear(neurons,1)

  x = torch.flatten(x)
  hidden_layer = tanh(hidden_layer(x))
  output_layer = sigmoid(output_layer(hidden_layer))

  return output_layer

In [7]:
forward(x,50)

tensor([0.5932], grad_fn=<MulBackward0>)

In [8]:
torch.manual_seed(160401003)
forward(x,50)

tensor([0.6701], grad_fn=<MulBackward0>)